### ISSUE TITLE
Reward icons are stuck and are not switching with the battlepass pages

### ISSUE THREAD

**Issue by KoltaiArmy** [GC-spigot/battle-pass#132]
**Describe the bug**
Hi! I dont know if this is a bug only for me, but any time I switch pages on battlepass tiers, the reward icons are just stuck. 
(for eg. the reward for Tier 2 is also showing up above Tier 11, etc.) 

**To Reproduce**
### free.yml
```
tiers:
  '2': # The tier number
    rewards: ['1'] # The reward numbers to give to the player (see rewards.yml).
    required-points: 120 # The amount of points the player must get to advance to the tier.
```
### premium.yml:
```
tiers:
  '36':
    rewards: ['5']
    required-points: 5000
```

**Screenshots / Video**
https://cdn.discordapp.com/attachments/614504514854191112/935497690891059241/2022-01-25_12-32-31.mp4

**Server Information (please complete the following information):**
- Server Version: [Purpur 1.16.5]
- Plugin Version: [3.6.7]
