### ISSUE TITLE
[Issue] PlaceholderAPI Endless Quests not working

### ISSUE THREAD

**Issue by Dagrond** [GC-spigot/battle-pass#161]
**Describe the bug**

placeholder_integer_ type quests are not working at all. For example: placeholder_integer_player_level.

**To Reproduce**
This is example quest what I've been using:
```
  1: # Quest id
    name: 'Reach Exp. Level 10' # The name given to the quest.
    type: placeholder_integer_player_level # Your quest
    variable: none
    required-progress: 10 # The level player should reach
    points: 10 # The amount of points that will be rewarded
    item: # The item that will be displayed in menus.
      material: experience_bottle:0
      amount: 1
      name: '&eExperienced'
      lore:
        - '&7Reach Exp. Level 10'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'
```
 
NOTE: I know that I can do this example by quest-type gain-experience. But this is just an example that shows that PAPI quests are not working. Any other placeholder is not working as well.

**Screenshots / Video**
This is my example of trying to complete this quest:
https://www.youtube.com/watch?v=MNKPWXamCEg
As you can see, if I type %player_level% in chat, the placeholder is parsed correctly (0:30 on the video).

**Server Information (please complete the following information):**
- Server Version: Pufferfish 1.18.2-63
- Plugin Version: BattlePass-3.7.8, PlaceholderAPI-2.11.1
