### ISSUE TITLE
Bukkit Tag System

### ISSUE THREAD

**Issue by Ste3et** [GC-spigot/battle-pass#200]
Can you please add support for the Bukkit Material Tag system to make some quest configurations easer?

Here is my demo configuration

```
17:
    name: 'Täglich - Kerzenschein'
    type: right-click-block
    variable:
      root: candle:0 OR white_candle OR orange_candle OR magenta_candle OR light_blue_candle OR yellow_candle OR lime_candle OR pink_candle OR gray_candle OR light_gray_candle OR cyan_candle OR purple_candle OR blue_candle OR brown_candle OR green_candle OR red_candle OR black_candle
      holding:
        item: flint_and_steel:0
    required-progress: 5
    points: 1
```

Here is the advanced config

```
17:
    name: 'Täglich - Kerzenschein'
    type: right-click-block
    variable:
      root: #minecraft:candles
      holding:
        item: flint_and_steel:0
    required-progress: 5
    points: 1
```

the code to get the Material tage is these

`
Bukkit.getTag(Tag.REGISTRY_BLOCKS, new NamespacedKey("minecraft", "candles"), Material.class);
`

regards
Ste3et_C0st
