### ISSUE TITLE
[Request] Wildcard variable for chestshop quests

### ISSUE THREAD

**Issue by tehsa** [GC-spigot/battle-pass#216]
Request: A wildcard variable similar to how `none` works in other quest types (e.g. `block-break` or `kill-mob`).

Reason/Issue: For quest types `chestshop_spend` and `chestshop_buy` the variable currently has to be set to one specific owner/client. This is possibly also valid for all other chestshop quest types that require users to interact with other players' shops. Setting `none` as variable does not work. 

This makes the quest type not ideal for strengthening overall user economy. In case the server used e.g. ten specific users for these quest types it would favor these users that get the promoted spot in either weekly or daily quest rotation. This in turn creates frustration for other users. 

Examples:

```
   8:
     name: 'Daily - Chestshop 1'
     type: chestshop_buy
     variable: none
     required-progress: 10
     points: 10
     item:
       material: chest:0
       name: '&eChestshop 1'
       lore:
         - '&Buy &e10 Items via chestshop'
         - '&810 Points'
         - '&7Progress &e%total_progress%&7/&e%required_progress%'
```
```
   9:
     name: 'Daily - Chestshop 2'
     type: chestshop_spend
     variable: none
     required-progress: 100
     points: 10
     item:
       material: chest:0
       name: '&eChestshop 2'
       lore:
         - '&7Spend &e100 currency in chestshops'
         - '&810 Points'
         - '&7Progress &e%total_progress%&7/&e%required_progress%'
```
