### ISSUE TITLE
[Issue] Some craft don't work

### ISSUE THREAD

**Issue by nicolas1920** [GC-spigot/battle-pass#229]
**Describe the bug**
Hello , some craft don't work I have check and  check again  , nothing change for :
-Red and blue wool , so I think all colour is same except  white because you craft it with string
-Dispenser
-dropper
-lever
-piston
-sticky piston
-Observer
-hooper
-repeater
-comparator
-tripwire_hook
-Jack'o'lantern
-redstone torch

Maybe other but I don't have test all item of minecraft x))) , I have use https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html for compare and I'm good normaly 

**To Reproduce**
```
  43:
    name: 'Test'
    type: craft
    variable: dropper
    required-progress: 4
    points: 10
    item:
      material: dropper
      name: '&etest'
      lore:
        - '&7Craftez &e4 &7dropper '
        - ''
        - '&7Progression &e%total_progress%&7/&e%required_progress%'
```

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: Spigot 1.18.2
- Plugin Version: 3.11.5
