### ISSUE TITLE
Quest "Crafting" works wrong

### ISSUE THREAD

**Issue by enels0n** [GC-spigot/battle-pass#237]
When crafting items, the quantity is not taken into account.

Video: https://youtu.be/Jr6gvY069Fw
Config:
```
  58:
    name: '&f'
    type: craft
    variable: iron_sword
    required-progress: 5
    points: 10
    item:
      material: iron_sword:0
      amount: 1
      name:  '&d✰10'
      lore:
        - '&eСоздайте 5 железных мечей'
        - ''
        - '&7Выполнение &e%total_progress%&7/&e%required_progress%'
```
Server Version:  git-Paper-245 (MC: 1.19.2)
Plugin Version: Latest 3.12.1
