### ISSUE TITLE
[Issue] Cactus / Sugar Cane not counting every time they are broken

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#263]
**Describe the bug**
When a player tries to break cactus / sugar_cane, it doesn't always count in a quest.

**To Reproduce**
```yaml
  64: # Quest id
    type: block-break
    variable: sugar_cane:0
    name: "Agriculture"
    required-progress: 200
    points: 5
    item:
      material: sugar_cane
      name: "&e&lAgriculture"
      lore:
        - ""
        - "&7Récolte &6%required_progress%&e cannes à sucre &7!"
        - ""
        - "&7Progression : &e%total_progress%&7/&6%required_progress%"
  65: # Quest id
    type: block-break
    variable: cactus:0
    name: "Agriculture"
    required-progress: 50
    points: 5
    item:
      material: cactus
      name: "&e&lAgriculture"
      lore:
        - ""
        - "&7Récolte &6%required_progress%&e cactus &7!"
        - ""
        - "&7Progression : &e%total_progress%&7/&6%required_progress%"
```

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
Paper 1.19.2
battle-pass-3.14.1
