### ISSUE TITLE
[Issue] Weeks being unlocked before previous week quests finished

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#265]
**Describe the bug**

When a players complete 7 weeks quests out of 10, the next week is unlocked

**To Reproduce**
I think you coded that when a players does 7 quests out of 8, it unlocks the next quest but it's not right : 
- When there is more than 7 week quests, that means a player can complete the 7 missions of his choice and then go to the next week, so i we have like the same quest between 2 weeks he can progress both of them

**Screenshots / Video**
Is is used with there parameters :
```yaml
  unlocks:
    require-previous-completion: true # Whether the user must complete all missions in the previous week to start the next week.
    lock-previous-weeks: false # Whether previous weeks will be locked when a new week is released.
```

Server Information (please complete the following information):
Paper 1.19.2
battle-pass-3.14.1
