### ISSUE TITLE
[Request] Add placeholder compatibility in item rewards

### ISSUE THREAD

**Issue by RSLuke** [GC-spigot/battle-pass#270]
**Describe the Request**

Just add a way so we can use placeholders in item custom names and lores, like this : 

```yaml
"22":
  type: item
  items:
    "1":
      material: paper
      amount: 1
      name: "&d%custom_placeholder%"
      lore:
        - ""
        - "&7%time%"
        - "&7%month%"
      glow: true
```
