### ISSUE TITLE
[Issue] Enchanting bug

### ISSUE THREAD

**Issue by memosoff** [GC-spigot/battle-pass#292]
1. When do quest enchant with event 'enchant' or 'enchant-anvil' no reaction to quest https://streamable.com/h8de9c (video from other issue but same problem)
```
type: enchant
  root: DURABILITY
  level: 1
  item: diamond_chestplate
name: Enchanter
required-progress:  1
points: 10
item:
  material: diamond_chestplate
  name: 'test'
  lore:
    - 'test'
```

2. When do quest enchant with event 'enchant-all' you can complete the quest without spending the enchantment book, just put the item that can't be enchanted on the anvil and click on the empty slot
https://youtu.be/a6LOvKFWDvI
