### ISSUE TITLE
[Issue] Actions - "[message] {message}" and "[menu] {exit}" in plugin not work

### ISSUE THREAD

**Issue by Futodama** [GC-spigot/battle-pass#314]
### Describe the bug

I improved the menu of your plugin to work with it and make it more interactive, but I ran into the fact that it is impossible to display messages or exit the menu by clicking the button in the menu. According to examples from WIKI, there is also no effect, even complete copying.

I really need the output of messages in the chat, it is through:
```
      actions:
        - '[message] {&e}'
```

But the plugin stubbornly doesn't work with the "actions" data.

### How to reproduce

Take that:

```
  '7':
    item:
      material: diamond:0
      customModelData: 172
      name: '&eWar Song'
      lore:
        - '&f'
      actions: 
        - '[message] {&eThe message}'
        - '[menu] {close}'
```

### Screenshots / Videos

https://drive.google.com/file/d/1fpS_TVE-kZxp_5hinrn7tK2xu7uetJn0/view?usp=share_link
https://user-images.githubusercontent.com/73364285/226848261-3c64637a-cbd2-4a13-9d37-66732aa07127.mp4

### Server Log

https://mcpaste.io/e025aa66425b36fb

**Comment by KPGTB** [comment]
Hey! You made a mistake during configuration. Section `actions` should be in `7` section, not in `item` section. It means, that your configuration should look like this
```
  '7':
    item:
      material: diamond:0
      customModelData: 172
      name: '&eWar Song'
      lore:
        - '&f'
    actions: 
        - '[message] {&eThe message}'
        - '[menu] {close}'
    ```
