### ISSUE TITLE
Change the reward system for more ease of use

### ISSUE THREAD

**Issue by austv** [GC-spigot/battle-pass#319]
### Describe the feature

I took a long time to understand how to setup the rewards (using the plugin for months now) and I have a sugest.

Instead editing two files, the rewards.yml and free.yml (or premium) to setup one reward, create the rewards inside the pass file.

For example, change this:
```
(rewards.yml)
'reward_1':
  type: item
  name: 'test'
  lore-addon:
    - '&7 - &e64x Irons'
  items:
    '1':
      material: iron_ingot:0
      amount: 64

'reward_2':
  type: item
  name: 'test'
  lore-addon:
    - '&7 - &e30 Diamonds'
  items:
    '1':
      material: diamond:0
      amount: 30

(free.yml)
tiers:
  '2':
    rewards: ['reward_1', 'reward_2]
    required-points: 150
```
to this:
```
tiers:
  '2':
    required-points: 150
    lore:
       - '&f 30x Diamonds'
       - '&f 64x Irons'
    rewards:
       - give %player% diamond 30
       - give %player% iron_ingot 64
```
Is very difficulty to understand this system and even after that, is confusing when you wanna add new more rewards because you need to change two files in a weird way, instead just one.

In my point of view, is more easy, less code up and more beautiful to see :)
