### ISSUE TITLE
Change Locked & Unlocked Item for each Tier

### ISSUE THREAD

**Issue by neooo191** [GC-spigot/battle-pass#339]
### Describe the feature

So atm u can only change the Locked/Unlocked Item for every tier (the minecart) but i think it would be very nice to change it per tier each so we can put the whatever we want in there for example for tier 1 a diamond sword and tier 2 a netherite ingot.. It would display nicely what the player will unlock

**Comment by KPGTB** [comment]
Hey! You can change the reward icon for a specific tier. It's well described in `BattlePass/passes/free.yml` in `tiers` section.

```
tiers:
  '10':
      rewards: ['1', '2', '3', '4']
      required-points: 500
      locked-tier-item: # You can specify any of the items in the 'items' section above per tier. They're completely optional for each tier.
        material: 'barrier:0'
        name: '&eTier %tier%'
        lore:
          - ''
          - '&7Rewards:'
          - '%lore_addon%'
          - ''
          - '&7Status: &cSpecial Locked Item'
```
