### ISSUE TITLE
Quests being completed multiple times

### ISSUE THREAD

**Issue by thewickening** [GC-spigot/battle-pass#379]
### Describe the bug

Sometimes on latest version, people are completing the same quest multiple times and getting a ton of levels.

### How to reproduce

Not able to reproduce, it is random.

### Screenshots / Videos

https://i.gyazo.com/thumb/1200/f9f3ca337d5617782ed5273ede532521-png.jpg

**Comment by WhatsTheBadNews** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/29821149/5e688a98-f97c-4aee-adf5-7cb27849b91a)

**Comment by SirvydasS** [comment]
SAME, major BUG¹

**Comment by GC-spigot** [comment]
@SirvydasS @WhatsTheBadNews @thewickening Does this happen with specific quests or all? Can one of you share a quest which this problem has happened with for sure, so we can test?

**Comment by WhatsTheBadNews** [comment]
> @SirvydasS @WhatsTheBadNews @thewickening Does this happen with specific quests or all? Can one of you share a quest which this problem has happened with for sure, so we can test?

```
  3: # Quest id
    type: kill-mob
    variable: blaze
    name: 'Week 1 - Blaze Massacre'
    required-progress: 960
    points: 150
    item:
      material: blaze_rod
      name: '&d&lQUEST: &fBlaze Massacre'
      lore:
        - '&8 » &7To complete this quest, you must'
        - '&8 » &7kill 960 blazes.'
        - ''
        - '&d&lINFORMATION'
        - '&8 » &7Points: &f150'
        - '&8 » &7Progress: &a%total_progress%&8/&c%required_progress%'
```
