### ISSUE TITLE
Suggestion: Add on quests "whitelisted-regions"

### ISSUE THREAD

**Issue by Ekkoy06** [GC-spigot/battle-pass#391]
### Describe the feature

Add on quests (daily and weekly) ``whitelisted-regions`` for more control over battlepass (kill x mobs on y region, bla bla)

**Comment by KPGTB** [comment]
Hey! You can configure these values in quest yml file using these sections:
- whitelisted-worlds
- blacklisted-worlds
- blacklisted-regions
- whitelisted-regions

Example:
```yaml
quests:
  1: # Quest id
    name: 'Week 1 - Miner' # The name given to the quest.
    type: block-break # The type of quest
    variable: coal_ore:0 # The block the player must break.
    whitelisted-regions: ["spawn", "mine"] # Progrress only in spawn and mine regions
    blacklisted-worlds: ["world_nether"] # Disable progress in world_nether
   ...
```
