### ISSUE TITLE
Endless quests using match and player_has_potioneffect does not work

### ISSUE THREAD

**Issue by z1haze** [GC-spigot/battle-pass#394]
### Describe the bug

Doing this from phone, sorry if it comes through weirdly formatted.

I am trying to implement some custom quests that rely on a player getting a potion effect. An example of these quests is below. This does not work though. I have tried various ways, such as putting the potion effect in thr variable, etc. Nothing works. I opened a ticket in the discord a month ago and did not get this resolved but was assured if I report it here I would get a resolution very quickly. I hope you can help with this, the issue is pretty straight forward and easy to replicate yourself. Iirc the configuration below will just immediately reward you the quest completion without even having the effect.
```
2:
    type: placeholderapi_match_player_has_potioneffect_hero_of_the_village
    name: 'The Hero Gotham Needs'
    required-progress: 1
    points: 3
    item:
      material: netherite_sword
      name: '&eThe Hero Gotham Needs'
      lore:
        - '&7To complete this quest, you must'
        - '&7defeat a village raid'
        - ''
        - '&7(&a%percentage_progress%&7)'
```

### How to reproduce

In my testing I created the above quest example as a daily quest and forced it to always show up in the dailies. I then just refresh the daily quests and at that moment it automatically completes the quest without my player having the effect. I tried through server restarts as well and same result.

**Comment by z1haze** [comment]
bump... please?

**Comment by GC-spigot** [comment]
So this is a configuration issue... you are not comparing this to anything. How would battlepass know that your quest is completed? The whole idea of `match` quest is to match it to something that you want. In your case:
```yaml
  2:
    type: placeholderapi_match_player_has_potioneffect_hero_of_the_village
    variable: 'yes'
```


Is the correct format. When player has effect, you will have a `yes` output from the placeholder, therefore you will be able to know when they have that potion effect.
