### ISSUE TITLE
Fix the MythicMobs hook

### ISSUE THREAD

**Issue by Superalex0102** [GC-spigot/battle-pass#399]
### Describe the bug

The newest BattlePass version doesn't work with the newest MythicMobs version.

### How to reproduce

MythicMobs-5.3.5
BattlePass-3.18.5

### Screenshots / Videos

```
  1:
    name: 'Hét - 1'
    type: mythicmobs_kill_mob
    variable: Warrior_3
    required-progress: 25
    points: 150
    item:
      material: diamond_helmet:0
      amount: 1
      name: '&e&lQUEST: &fMob ölés'
      lore:
        - ' &8» &7Ölj meg 25 Warrior (Level 3) mobot'
        - ''
        - '&e&lINFORMÁCIÓ:'
        - ' &8» &7Típus: &fIngyenes'
        - ' &8» &7Pont: &f150'
        - ' &8» &7Teljesítmény: &a%percentage_progress%'
```
