### ISSUE TITLE
Plugin not working latest version.

### ISSUE THREAD

**Issue by dahbawz** [GC-spigot/battle-pass#423]
### Describe the bug

Plugin disabled latest version.

### How to reproduce

Paper 1.19.3

Latest bp version.

### Server Log

https://mcpaste.io/83884a18a779d404

**Comment by Erdi-GitHub** [comment]
Check your lang.yml, do you have the following lines in it?
```yaml
bpa:
  command:
    - ''
    - '&bBattlePass Admin Help:'
    - '/bpa - This page.'
    - '/bpa reload - Reloads all the reloadable files.'
    - '/bpa editor - Open In-Game quests editor.'
    - '/bpa set pass <player/online/all> <pass type> - Sets a player/group of players'' pass type.'
    - '/bpa set points <player> <points> - Set a players points.'
    - '/bpa give points <player> <points> - Give a player points.'
    - '/bpa delete user <player> - Delete all data of a user.'
    - '/bpa quest ids <week> - List all of the weeks quest ids and their names.'
    - '/bpa daily quest ids - List all of the daily quest ids and their names.'
    - '/bpa reset quest <player> <week> <id> - Resets a specific quest of a player.'
    - '/bpa progress quest <player> <week> <quest id> <amount> - Progresses a specific quest of a player.'
    - '/bpa progress daily quest <player> <quest id> <amount> - Progress a specific quest of a player.'
    - '/bpa refresh daily quests - Refresh daily quests.'
    - '/bpa new season - Resets user tiers, pending rewards and points.'
    - '/bpa material <block/item> - Get the config name of the item you''re holding or block you''re looking at.'
    - '/bpa bypass locked quests <player> - Allows the player to bypass week locks and complete quests anyway.'
    - '/bpa close menu <player> - Closes a player''s open menu'
  internal-balance:
    - '/bpa give balance <player> <amount> - Gives internal balance.'
    - '/bpa remove balance <player> <amount> - Takes away internal balance.'
    - '/bpa set balance <player> <amount> - Sets a player''s internal balance.'
```
