### ISSUE TITLE
1.8 | STAINED_GLASS_PANE:DATA <Bug Issue>

### ISSUE THREAD

**Issue by ItzFabb-uwu** [GC-spigot/battle-pass#427]
### Describe the bug

There's an issue with the ID:DATA with the 1.8.9 version of Battlepass it won't recognize the 'DATA' of the item, 
![image](https://github.com/GC-spigot/battle-pass/assets/58950562/149b4737-bd1c-48ec-88a3-57b5238cd284)
![image](https://github.com/GC-spigot/battle-pass/assets/58950562/2eb54206-26bf-49a5-8fef-96e85a1905d6)

```
menu-title: 'Battlepass'
menu-rows: 6

menu:
  '0':
    item:
      material: STAINED_GLASS_PANE:3
      name: ' &R'
      lore: []
    actions: []
  '1':
    item:
      material: STAINED_GLASS_PANE:3
      name: ' &R'
      lore: []
    actions: []
  '7':
    item:
      material: STAINED_GLASS_PANE:3
      name: ' &R'
      lore: []
    actions: []
  '8':
    item:
      material: STAINED_GLASS_PANE:3
      name: ' &R'
      lore: []
    actions: []
  '9':
    item:
      material: STAINED_GLASS_PANE:3
      name: ' &R'
      lore: []
    actions: []
  '11':
    item:
      material: STAINED_GLASS_PANE:8
      name: ' &R'
      lore: []
    actions: []
  '12':
    item:
      material: STAINED_GLASS_PANE:8
      name: ' &R'
      lore: []
    actions: []
```

### How to reproduce

Try it using 1.8.9 battlepass 4.0.8
