### ISSUE TITLE
Integer Placeholders do not update quest progress

### ISSUE THREAD

**Issue by mbusson** [GC-spigot/battle-pass#448]
### Describe the bug

Paper 1.20.2, BP 4.0.15

I've been having this issue with many of my quests -- though the placeholder returns an integer, quests do not progress and do not complete.

Example config:
```
  74:
    type: placeholderapi_integer_statistic_horse_one_cm
    variable: ''
    name: "Equestrian"
    required-progress: 50000
    points: 20
    item:
      material: apple
      name: "&7Equestrian"
      lore:
      - '&fRide a horse for 500m'
      - '%progress_bar% &7(&a%percentage_progress%&7)'
```
![image](https://github.com/GC-spigot/battle-pass/assets/17831738/79b5a9f8-2b4f-4569-8ce9-26412a272cf4)

Other example broken placeholders:
```
placeholderapi_integer_VotingPlugin_alltimetotal
placeholderapi_integer_vault_eco_balance_fixed
```

### How to reproduce

Make a quest with `placeholderapi_integer_` type prefix

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/17831738/79b5a9f8-2b4f-4569-8ce9-26412a272cf4)

![image](https://github.com/GC-spigot/battle-pass/assets/17831738/02c0e2f0-fb3d-4bd3-a17b-fbbb8d084441)
![image](https://github.com/GC-spigot/battle-pass/assets/17831738/8ee8e8a3-ffd6-4945-9fce-14a493ae2142)
![image](https://github.com/GC-spigot/battle-pass/assets/17831738/8dff8333-17d9-41fb-be90-9c7a22fdb544)

### Server Log

https://mcpaste.io/da799f5a804f9dba
