### ISSUE TITLE
Character array contains more than one decimal point

### ISSUE THREAD

**Issue by austv** [GC-spigot/battle-pass#455]
### Describe the bug

My console spam this error for each player in the server. Check the log.

### How to reproduce

The odd is I have only one quest using placeholderapi quest and is not a float number.

```
  6:
    name: 'Contribuição'
    type: placeholderapi_integer_**VotingPlugin_Total_Daily**
    variable: none
    required-progress: 6
    points: 20
    item:
       material: paper:0
       amount: 1
       name: '&eContribuição'
       lore:
         - '{#61FAB3}Vote &7no servidor.'
         - ''
         - '&f Progresso: &e%total_progress%&8/&e%required_progress%'
```

### Server Log

https://mclo.gs/JIOHgN6
