### ISSUE TITLE
whitelist region

### ISSUE THREAD

**Issue by SirJben** [GC-spigot/battle-pass#464]
### Describe the feature

We have a blacklisted region that works perfectly. However, having a whitelisted region as well would be more convenient. Managing numerous regions, especially those you don't want included, can create a messy configuration.

**Comment by Baixa123321** [comment]
It would be cool to add a whitelist of worlds too, for missions on specific worlds, like mining in the mining world

**Comment by KPGTB** [comment]
Hey! You can configure these values in quest yml file using these sections:
- whitelisted-worlds
- blacklisted-worlds
- blacklisted-regions
- whitelisted-regions

Example:
```yaml
quests:
  1: # Quest id
    name: 'Week 1 - Miner' # The name given to the quest.
    type: block-break # The type of quest
    variable: coal_ore:0 # The block the player must break.
    whitelisted-regions: ["spawn", "mine"] # Progrress only in spawn and mine regions
    blacklisted-worlds: ["world_nether"] # Disable progress in world_nether
   ...
```
