### ISSUE TITLE
Custom Quest Type API not working

### ISSUE THREAD

**Issue by Timongcraft** [GC-spigot/battle-pass#483]
Hello, I'm trying to trigger quests using the API but I don't get any indication in-game that they have been completed when the trigger method is being executed but I can see that the quest exist in the quest menu.

```java
public class Quest extends ActionQuestExecutor {

    private final String questName;

    public Quest(String questName, JavaPlugin plugin) {
        super(plugin, questName);
        this.questName = questName;
    }

    public void trigger(Player player) {
        execute(questName, player, result -> result);
    }

}

public class QuestManager {

    private final Map<QuestType, Quest> quests = new HashMap<>();

    public void loadQuests(JavaPlugin plugin) {
        ActionRegistry actionRegistry = BattlePlugin.getPlugin().getActionRegistry();

        for (QuestType questType : QuestType.values()) {
            Quest quest = new Quest(questType.getQuestName(), plugin);
            actionRegistry.quest(instance -> quest);
            quests.put(questType, quest);
        }
    }

    public void triggerQuest(QuestType type, Player player) {
        quests.get(type).trigger(player);
    }

}
```

~/plugins/BattlePass/quests/daily-quests.yml
```yml
quests:
  5:
    type: placeholder
    variable: none
    name: 'placeholder'
    required-progress: 1
    points: 15
    item:
      material: emerald
      name: 'placeholder'
      lore:
        - 'placeholder'
        - 'placeholder'
```
