### ISSUE TITLE
Killing a mob or mythicmobs with custom sword using customModelData

### ISSUE THREAD

**Issue by giovannispano** [GC-spigot/battle-pass#494]
### Describe the feature

Add the ability to decide whether a mythicmobs mob or minecraft mob is killed using custom swords using the formatting of the customModelData in the holding property

**Comment by KPGTB** [comment]
Hey! I added new variable - `holding.model` in every action, so you can change required custom model data of held item to progress quest. It will be available in the next update

**Comment by BlackGiok** [comment]
Thank u

**Comment by BlackGiok** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/38602287/a9f4e3b7-fa17-4180-adef-420624c3dc00)
It's correct this example? Because it's not working

**Comment by KPGTB** [comment]
Hey! It seems that GC didn't add your feature to the latest update. You need to wait for merge. When GC merge PR with your feature, this issue will be automatically closed.

**Comment by BlackGiok** [comment]
hi, any news?

**Comment by BlackGiok** [comment]
![image](https://github.com/GC-spigot/battle-pass/assets/38602287/986c524c-4fb4-47ca-832b-f17627c02aa2)
Hi, i don't understand how it works

**Comment by KPGTB** [comment]
Hey! It seems that everything works fine. Quest should progress when you kill mob using netherite sword with custom model data 1087. Here is also example on which I tested it (netherite sword + custom model data 100 - killing zombie)

((I know that you're testing it on mythicmobs, but it doesn't matter. It uses same method)

```
 6:
        name: "Week 2 - Grinder"
        type: kill-mob
        variable:
            root: zombie
            holding:
                item: "netherite_sword:0"
                model: 100
        required-progress: 10
        points: 10
        item:
            material: gold_sword:0
            name: "&eGrinder"
            lore:
                - "&7Kill &e10 zombies"
                - ""
                - "&7Progress &e%total_progress%&7/&e%required_progress%"
```
