### ISSUE TITLE
Multiple item-names with variable-option "holding" not working properly.

### ISSUE THREAD

**Issue by leon37921** [GC-spigot/battle-pass#498]
### Describe the bug

I want to create a "log-strip" quest where you have to strip logs with an axe. It should be possible with any axe, not just one.
But it only adds progress for the first entry (diamond_axe), not for the second entry (netherite_axe). 
my quest:
```
    type: right-click-block
    variable:
      root: oak_log
      holding:
        item: diamond_axe:0 OR netherite_axe:0
```
Is this a bug or has it not been implemented yet?

BattlePass version 4.2.16
This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)

### How to reproduce

1. add Quest with "type: right-click-block" and with variables listed above
2. reload plugin /bpa reload
3. use diamond_axe and netherite_axe on oak_log (right-click)
