### ISSUE TITLE
Textures and items wonky and error

### ISSUE THREAD

**Issue by iFranticman** [GC-spigot/battle-pass#510]
### Describe the bug

Massive error in console on displaying in battlepass

### How to reproduce

update to newest version and type /bp and go to quests

### Screenshots / Videos

https://pastebin.com/W0RdzB7r

### Server Log

https://pastebin.com/W0RdzB7r

**Comment by KPGTB** [comment]
Hey! Can you check, if adding `completionMaterial: ""` to `current-season` section in `settings.yml` will fix this problem? It should look like this:
```
current-season:
  time-zone: 'Europe/Oslo' # The timezone for week releases to be based off.
  start-date: '06/06/2020' # This is what all of the week releases are based off. Format: dd/mm/yyyy
  ....
  completionCustomModelData: 0
  completionMaterial: "" # Use "" to disable
  notify-at-percentages: [10, 25, 50, 75, 100]
  ...
```
