### ISSUE TITLE
Developer’s problem about using API

### ISSUE THREAD

**Issue by Kugana** [GC-spigot/battle-pass#519]
### Describe the bug

Hello, I have some BattlePass API's Question
### QuestEvent
```java 
public class BlockBreakQuest extends ActionQuestExecutor {

    
    public BlockBreakQuest(BattlePlugin plugin) {
        super(plugin, "FOLDoomDay");
    }
    DoomDay plugin = (DoomDay) Bukkit.getServer().getPluginManager().getPlugin("FOLDoomDay");
    //@SuppressWarnings("deprecation") 
    @EventHandler//(ignoreCancelled = true)
    public void ontest(PlayerInteractEvent e) {
        Player p = e.getPlayer();
        data data = new data(plugin);
        if (e.getAction() == Action.RIGHT_CLICK_BLOCK) {
            if (!(e.getHand() == EquipmentSlot.OFF_HAND)) {
        for (String core : data.getLoot().keySet()) {

            LootUtil lu = (LootUtil) data.getLoot().get(core);

            if (lu.getLocation().equals(e.getClickedBlock().getLocation())) {
                p.sendMessage("test");
                super.execute("click-loot", p, result -> {
                    return result.root(e.getClickedBlock());
                }, replacer -> replacer.set("loot", e.getClickedBlock().getType()));
                return;
              }
            }
          }
        }
        
    }
}
```
### Registry
```java 
public void CheckBattlePass() {
        if (getServer().getPluginManager().getPlugin("BattlePass") != null) {
            ActionRegistry actionRegistry = BattlePlugin.getPlugin().getActionRegistry();
            actionRegistry.hook("FOLDoomDay", plugin -> new BlockBreakQuest((BattlePlugin) plugin));
            actionRegistry.register();
            
        }
    }
```
and this is my quest 
```yaml 
  4: # Quest id
    type: click-loot
    variable: none
    name: 'click-loot-test'
    required-progress: 200
    points: 10
    item:
      material: stone_sword
      name: '&eclick-loot-test'
      lore:
        - '&7To complete this quest, you must'
        - '&7click 200 loot box'
        - ''
        - '&7(&a%percentage_progress%&7)'
```
This is my current code, is this right?
because in the server, when I click my loo, quest not work 

```java 
if (lu.getLocation().equals(e.getClickedBlock().getLocation())) {
     //I'm sure I've entered this cycle
}
```
