### ISSUE TITLE
[Request] Conditions and mcMMO support

### ISSUE THREAD

**Issue by austv** [GC-spigot/battle-pass#52]
1. Support for mcMMO, for XP gain, etc.
2. Conditions, same as AdvancedEnchantments. For example, %player world% = world_the_end : %allow%

 AdvancedEnchantments has a lot of conditions and would be nice if I can use them in battle pass, not only related to world. Would be nice if we be able to do this:

```
name: 'End Farm'
    type: block-place
    variable: end_stone:0, oak_leaves:0, obsidian:0 ##I added some blocks here, idk if is already possible but if is not is a good feature too
    required-progress: 10
    points: 10
    condition:
      - '%player world% = world_the_end : %allow%'
    item:
      material: end_stone:0
      name: '&eEnd farm'
      lore:
        - '&Build a complete and funcional Enderman Farm.'
        - ''
        - '&7Progress &e%total_progress%&7/&e%required_progress%'
```
