### ISSUE TITLE
crayzcrates task per piece

### ISSUE THREAD

**Issue by 1strk0** [GC-spigot/battle-pass#542]
### Describe the feature

For example, I add the crazycrates task, it will open it once from the event vault, but there is no result.

**Comment by KPGTB** [comment]
Hey! I don't know what you mean. Can you describe it once again? There is `crazycrates_open` quest with crate name as root variable

**Comment by 1strk0** [comment]
let me give an example 
I want him to open 1 from the legendary vault and I want to add it as a task to bp

**Comment by KPGTB** [comment]
```
type: crazycrates_open
variable: NAME_OF_CREATE
required-progress: 1
```

**Comment by 1strk0** [comment]
didn't work

**Comment by KPGTB** [comment]
Here is example quest that I created and it works nice. Please notice that variable is a crate id which is a name of file with configuration of that crate

```
    1: # Quest id
        name: "Week 1 - Crates" # The name given to the quest.
        type: crazycrates_open # The type of quest
        variable: CrateExample # The block the player must break.
        required-progress: 10 # The amount of times the player should break the coal ore block.
        points: 10 # The amount of points that will be rewarded
        item: # The item that will be displayed in menus.
            material: chest:0
            amount: 1
            name: "&eCrate"
            lore:
                - "&7Open 10 basic crates"
                - ""
                - "%progress_bar% &7(&a%percentage_progress%&7)" 
          ```
