### ISSUE TITLE
Add placeholderAPI supports for passes menus

### ISSUE THREAD

**Issue by lulu2002** [GC-spigot/battle-pass#560]
### Describe the feature

Currently in passes, it's not accept any placeholderapis, like

```yaml
items:
  doesnt-have-pass-item: 
    material: 'barrier:0'
    name: '&6Pass %tier%'
    lore:
      - ''
      - '%lore_addon%'
      - ''
  locked-tier-item: 
    material: 'furnace_minecart:0'
    name: '&6Pass %tier%'
    lore:
      - '%lore_addon%'
      - ''
      - '%battlepass_pass_type%' #<- not working (just an example, I want to use other placeholders from placeholder api)
```
