### ISSUE TITLE
Add anti abuse system to block-place

### ISSUE THREAD

**Issue by leon37921** [GC-spigot/battle-pass#564]
### Describe the bug

You can cheat in the quests with type "block-place" and "craft" by placing one block, breaking it and repeat or craft/uncraft i.e.  one emerald-block over and over again to gain quest-progress.
Tested in creative and survival gamemode.

plugins:
```
[23:08:12 INFO]: Server Plugins (5):
[23:08:12 INFO]: Bukkit Plugins:
[23:08:12 INFO]:  - BattlePass, BeautyQuests, Citizens, LuckPerms, PlaceholderAPI

```
Battlepass version: 4.5.6
`[23:13:24 INFO]: This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)`
No errors in console

### How to reproduce

1. Create a quest with type: block-place or craft
2. Place one block, mine it, repeat that step. 
or craft an emerald-block 5 times with the same 9 emeralds.
3. You get quest-progress.
test-quests:
```
quests:
  '15':
    type: block-place
    variable: OAK_SAPLING
    name: place saplings           
    required-progress: 5                   
    points: 0
    item:                                                    
      material: oak_sapling
      name: 'place saplings'
      lore:
      - '%progress_bar% &8[&a%percentage_progress%&8]'
      - '&7Fortschritt &2%total_progress%&8/&7%required_progress%'
  '16':
    type: block-place
    variable: GOLD_BLOCK
    name: place gold-blocks
    required-progress: 5
    points: 0
    item:
      material: GOLD_BLOCK
      name: 'place gold blocks'
      lore:
      - '%progress_bar% &8[&a%percentage_progress%&8]'
      - '&7Fortschritt &2%total_progress%&8/&7%required_progress%'
  '17':
    type: craft
    variable: EMERALD_BLOCK
    name: craft emerald blocks
    required-progress: 5
    points: 0
    item:
      material: EMERALD_BLOCK
      name: 'craft emerald blocks'
      lore:
      - '%progress_bar% &8[&a%percentage_progress%&8]'
      - '&7Fortschritt &2%total_progress%&8/&7%required_progress%'

```
[settings.yml](https://pastebin.com/cLCGpsv3)

### Screenshots / Videos

https://github.com/user-attachments/assets/56a6b276-5d14-4d16-a651-391b5e82f487
