### ISSUE TITLE
Static items in rewards menu closing the GUI

### ISSUE THREAD

**Issue by bobhenl** [GC-spigot/battle-pass#574]
### Describe the bug

Hello, I have set this in the rewards menu:
```yml

static-items:
  progress-track-locked-item:
    material: 'red_dye'
    customModelData: 4003
    name: '&f&lTier %tier%'
  progress-track-unlocked-item:
    material: 'lime_dye'
    customModelData: 4001
    name: '&f&lTier %tier%'

```
But when users click it, it closes menu, why please? Other items do not close it, should I add there some empty action or so? But I tried to add it under the name:     actions: [] but it didn't work

Menu is also closed when clicking on rewards that I don't have unlocked, but why? I have set close-on-reward-claim: false

### How to reproduce

Try my settings or even the default one prob?
