### ISSUE TITLE
Block-place issues 

### ISSUE THREAD

**Issue by lDoomerl** [GC-spigot/battle-pass#588]
### Describe the bug

I have some issues with `block-place` quest type.
Simple weekly quest to broke 400 amethyst block, but the progress doesn't move at all.
I tried to change it to `block-break` but the result was the same. 

`Current Purpur Version:` 1.21-2261-14136b8 (MC: 1.21)
`BattlePass version` 4.6.9

### How to reproduce

```yaml
 '7':
    type: block-place
    variable: amethyst_block
    name: '&eНеделя 1 - Установка аметистового блока'
    required-progress: 400
    points: 90
    item:
      material: amethyst_block:0
      name: '{#9e3dcc}Поставить аметистовый блок'
      lore:
      - '&fПоставьте аметистовый блок 400 раз'
      - '&fНаграда за выполнение: &e1200 монет'
      - ''
      - '&7Прогресс &e%total_progress%&7/&e%required_progress%'

```

### Server Log

No errors or warns in console.
