### ISSUE TITLE
ShopGui+ and Jobs not working

### ISSUE THREAD

**Issue by Superalex0102** [GC-spigot/battle-pass#97]
**Describe the bug**
ShopGui+ and Jobs variables not working

**To Reproduce**

week2-quests.yml:
```
  2: # Quest id
    name: 'Hét - 2' # The name given to the quest.
    type: shopguiplus_buy # The type of quest
    variable:
      root: TRIPWIRE_HOOK
      shop: keys
      item-id: 2
    required-progress: 100 # The amount of times the player should break the coal ore block.
    points: 50 # The amount of points that will be rewarded
    item: # The item that will be displayed in menus.
      material: tripwire_hook:0
      amount: 1
      name: '&eVásárlás'
      lore:
        - '&7Vásárolj &e100 Dallas Láda kulcsot'
        - '&ea boltból. (/shop)'
        - ''
        - '%progress_bar% &7(&a%percentage_progress%&7)' # If you wish, you can use a progress/required (23/1000) style format instead. Take a look a bit further down for examples.
```

shops.yml:
```
  keys:
    name: "Kulcs Bolt"
    size: 36
    fillItem:
        material: STAINED_GLASS_PANE
        damage: 15
        name: " "
    buttons:
      goBack:
        slot: 31
      previousPage:
        slot: 36
      nextPage:
        slot: 45
    items:
      1:
        type: item
        item:
          material: TRIPWIRE_HOOK
          quantity: 1
          name: "&bBexar Crate Kulcs"
        buyPrice: -1
        sellPrice: -1
        slot: 12
      2:
        type: command
        item:
          material: TRIPWIRE_HOOK
          quantity: 1
          name: "&dDallas Crate Kulcs"
        commands:
          - "crazycrate give p dallas %AMOUNT% %PLAYER%"
        commandsLimit: 64
        buyPrice: 1000000000
        runSingleCommand: true
        sellPrice: -1
        slot: 13
      3:
        type: command
        item:
          material: TRIPWIRE_HOOK
          quantity: 1
          name: "&6Harris Crate Kulcs"
        commands:
          - "crazycrate give p harris %AMOUNT% %PLAYER%"
        commandsLimit: 64
        buyPrice: 10000000000
        runSingleCommand: true
        sellPrice: -1
        slot: 14
```
jobs:
```
  4: # Quest id
    name: 'Hét - 2' # The name given to the quest.
    type: jobs_gain_exp # The type of quest
    variable: 'Woodcutter' # The block the player must break.
    required-progress: 2000 # The amount of times the player should break the coal ore block.
    points: 100 # The amount of points that will be rewarded
    item: # The item that will be displayed in menus.
      material: iron_axe:0
      amount: 1
      name: '&eMunka'
      lore:
        - '&7Szerezz &e2000 xp-t a'
        - '&efavágó munkánál'
        - ''
        - '%progress_bar% &7(&a%percentage_progress%&7)' # If you wish, you can use a progress/required (23/1000) style format instead. Take a look a bit further down for examples.
```

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Paper-1.12.2-b1618.jar
- battle-pass-3.5.11.jar
